name = "conceptualized-self"

kv_namespaces = [
  { binding = "johari", id = "9211972d93034bd4ab58197ea2cd4a64", preview_id = "3cb7156fc9094cdb9eee995bfb6ff50d" }
]

main = ".cloudflare/worker.js"
site.bucket = ".cloudflare/public/"
compatibility_date = "2023-11-18"

[env.production]
kv_namespaces = [
    { binding = "johari", id = "9211972d93034bd4ab58197ea2cd4a64" }
]

